### ISSUE TITLE
Type com.bumptech.glide.GeneratedAppGlideModuleImpl is defined multiple times

### ISSUE THREAD

**Issue by VicMikhailau** [nikhiljainlive/blockies_android#2]
Hi,

There is some conflict in the App Relese mode (see similar issue and resolution for one - https://github.com/bumptech/glide/issues/4984)

My App Gradle:
```
    implementation("com.github.bumptech.glide:glide:4.16.0")
    implementation("com.github.bumptech.glide:okhttp3-integration:4.16.0")
    ksp("com.github.bumptech.glide:ksp:4.16.0")
    ...
    implementation ("com.github.nikhiljainlive.blockies_android:blockiesglide:v0.2.0")
```

Error in Release Mode:

`Type com.bumptech.glide.GeneratedAppGlideModuleImpl is defined multiple times: /.gradle/caches/transforms-3/be5a81f2e2d6e1b79a1906aba1059ff4/transformed/blockiesglide-v0.2.0-runtime.jar:com/bumptech/glide/GeneratedAppGlideModuleImpl.class, /app/build/intermediates/classes/Release/transformtReleaseClassesWithAsm/dirs/com/bumptech/glide/GeneratedAppGlideModuleImpl.class`

**Comment by nikhiljainlive** [comment]
Okay, let me check.

**Comment by nikhiljainlive** [comment]
@VicMikhailau This has been fixed in the latest version v0.2.1 of the library. you can check if you're facing the same issue. 
The change is AppGlideModule has been replaced with LibraryGlideModule so the client need to implement AppGlideModule in their application module.

**Comment by nikhiljainlive** [comment]
Closing this issue. If the issue persists, feel free to open this issue.

**Comment by VicMikhailau** [comment]
@nikhiljainlive Thank you!
